/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "First of many": "第一个",
    "Achievement Finished": "成就完成",
    "The server I exist in": "我所在的服务器",
    "+ Unlock 2nd": "+ 解锁第 2",
    "+ Unlock 3rd": "+ 解锁第 3",
    "+ Unlock Stellar": "+ 解锁恒星",
    "0 undefined": "0 未定义",
    "1.005x for each achievement": "每项成就 1.005x",
    "A challenge please!": "请挑战！",
    "A start of new Era": "新时代的开始",
    "All that progress gone...": "所有的进步都消失了......",
    "And still no major inflation at stock market???": "股市仍然没有出现重大通胀？？？",
    "Bitcoin Achievements": "比特币成就",
    "Each Mastery has 3 Milestones and each Mastery it gets more harder to gain new Milestones": "每个精通都有 3 个里程碑，每个精通都会更难获得新的里程碑",
    "Elon would be proud": "埃隆会感到自豪",
    "Ethereum Achievements": "以太坊成就",
    "Fork your first Bitcoin!": "分叉你的第一个比特币！",
    "Funnily Rich": "有趣的富有",
    "I own more than I can count": "我拥有的多得数不过来",
    "In this video I gave away 1,000 Bitcoin to a random subscriber": "在这段视频中，我向随机订阅者赠送了 1,000 个比特币",
    "Is this currency even worth of grind?": "这种货币还值得磨炼吗？",
    "Is this real?": "这是真的吗？",
    "Lumen is pleased": "流明很高兴",
    "Main Progression": "主要进展",
    "Mastery Achievements": "精通成就",
    "More worth than Earth": "比地球更有价值",
    "More worth than Observable Universe": "比可观测宇宙更有价值",
    "Need 0.000 Points to Tier Up": "需要 0.000 点数才能升级",
    "Okay I was kidding...": "好吧我是开玩笑的...",
    "Points": "点数",
    "Points / sec": "点/秒",
    "Produce your first Stellar!": "制作你的第一个恒星！",
    "Progression": "进展",
    "Racking these Tiers": "整理这些层",
    "Reset EVERYTHING in exchange for a Tier for further progress": "重置一切以换取进一步进步的等级",
    "Rich again": "再次富有",
    "Richer than Elon Musk": "比埃隆·马斯克更有钱",
    "Richer than MrBeast?": "比野兽先生更有钱？",
    "Satoshi upper limit": "聪上限",
    "Speedrunning through": "极速跑过",
    "Stellar": "恒星",
    "Stellar / sec": "恒星/秒",
    "Stellar Achievements": "辉煌成就",
    "Stopppp.....": "停止吧……",
    "That was easy": "那很简单",
    "That was even easier!": "那更容易了！",
    "The gods are pleased": "大神们很高兴",
    "They forgot to limit my Ethereum manufacturing": "他们忘记限制我的以太坊制造",
    "Thousand": "千",
    "Tier": "等级",
    "Tier Achievements": "等级成就",
    "Tier Milestones": "级别里程碑",
    "Tier Milestones are sorted into Masteries.": "等级里程碑被分类为精通。",
    "TM Sets unlocked:": "TM 套装已解锁：",
    "Uncle Satoshi would be proud": "中本聪叔叔会感到自豪",
    "Unfunnily Rich": "无趣的富有",
    "Wealthy": "富有",
    "What's this?": "这是什么？",
    "Where do you even get all of this?": "你从哪里得到所有这些？",
    "Wow.": "哇。",
    "You are at Tier": "您处于层级",
    "You generate": "你生成",
    "You produce": "你生产",
    "+ Unlock Accelerant": "+ 解锁加速剂",
    "+ Unlock Stellar Automator": "+ 解锁恒星自动机",
    "+ Unlock Stellar Magnitude": "+ 解锁恒星星等",
    "Have more than 5 achievements": "拥有5项以上成就",
    "Bronze Mastery": "青铜精通",
    "Download Game": "下载游戏",
    "Mute": "静音",
    "Unmute": "播放",
    "Ethereum": "以太坊",
    "Ethereum / sec": "以太坊 / 秒",
    "Is this game actually this easy?": "这个游戏真的这么简单吗？",
    ", which gives": "，给予",
    "Off": "关闭",
    "On": "打开",
    "Stellar Automator": "恒星自动机",
    "Your Stellar Magnitude is": "你的恒星星等是",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "The Stellar Lumen : RE": "恒星流明：RE",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '←': '←',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "INF-": "无限-",
    "INF^": "无限^",
    "Neural Network v": "神经网络 v",
    "Wealthy^": "富有^",
    "Achievements: ": "成就: ",
    "Tier Up #": "提升层级 #",
    "Your acheivements raise Point generation by ^": "您的成就使 点数 生成增加 ^",
    "More Layers v": "更多的层 v",
    "Cheaper Components v": "更便宜的组件 v",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换音乐: ",
    "Mainframe-CFAH ": "大型机-CFAH ",
    "Defragmentation v": "碎片整理 v",
    "Limit ": "上限 ",
    "Formula: ": "公式: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " Stellar Buyable": " 恒星可购买",
    " Stellar buyable": " 恒星可购买",
    "x Stellar Magnitude limit": "x 恒星星等限制",
    " Ethereum buyable": " 以太坊可购买",
    " Stellar Magnitude Increase": " 恒星星等增加",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)$/,
    /^\/([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^\(([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\(([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Manufacture (.+) Ethereum!$/, '生产 $1 以太坊！'],
    [/^Obtain Tier (.+)!$/, '获得层级 $1！'],
    [/^Need (.+) Points to Tier Up$/, '需要 $1 点数以提升层级'],
    [/^Fork (.+) Bitcoin!$/, '分叉 $1 比特币！'],
    [/^Produce your first Stellar!$/, '产生你的第 1 颗恒星！'],
    [/^Produce (.+) Stellar!$/, '产生 $1 恒星！'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^x(.+) Point Generation$/, 'x$1 点数生成'],
    [/^x(.+) Stellar Production$/, 'x$1 恒星生产'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) of ([\d\.,]+)$/, '$1 \/ $2'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+ Unlock Stellar$/, '\+ 解锁恒星'],
    [/^\+ Unlock Ethereum$/, '\+ 解锁以太坊'],
    [/^Copy of Stellar$/, '恒星副本'],
    [/^(.+) OoMs$/, '$1 OoMs'],
    [/^(.+) Stellar$/, '$1 恒星'],
    [/^(.+) Ethereum$/, '$1 以太坊'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^TIER ([\d\.,]+)$/, '层级 $1'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);